// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	bytes "github.com/berachain/beacon-kit/mod/primitives/pkg/bytes"
	mock "github.com/stretchr/testify/mock"
)

// WriteOnlyStateRoots is an autogenerated mock type for the WriteOnlyStateRoots type
type WriteOnlyStateRoots struct {
	mock.Mock
}

type WriteOnlyStateRoots_Expecter struct {
	mock *mock.Mock
}

func (_m *WriteOnlyStateRoots) EXPECT() *WriteOnlyStateRoots_Expecter {
	return &WriteOnlyStateRoots_Expecter{mock: &_m.Mock}
}

// UpdateStateRootAtIndex provides a mock function with given fields: _a0, _a1
func (_m *WriteOnlyStateRoots) UpdateStateRootAtIndex(_a0 uint64, _a1 bytes.B32) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateRootAtIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bytes.B32) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteOnlyStateRoots_UpdateStateRootAtIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateRootAtIndex'
type WriteOnlyStateRoots_UpdateStateRootAtIndex_Call struct {
	*mock.Call
}

// UpdateStateRootAtIndex is a helper method to define mock.On call
//   - _a0 uint64
//   - _a1 bytes.B32
func (_e *WriteOnlyStateRoots_Expecter) UpdateStateRootAtIndex(_a0 interface{}, _a1 interface{}) *WriteOnlyStateRoots_UpdateStateRootAtIndex_Call {
	return &WriteOnlyStateRoots_UpdateStateRootAtIndex_Call{Call: _e.mock.On("UpdateStateRootAtIndex", _a0, _a1)}
}

func (_c *WriteOnlyStateRoots_UpdateStateRootAtIndex_Call) Run(run func(_a0 uint64, _a1 bytes.B32)) *WriteOnlyStateRoots_UpdateStateRootAtIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(bytes.B32))
	})
	return _c
}

func (_c *WriteOnlyStateRoots_UpdateStateRootAtIndex_Call) Return(_a0 error) *WriteOnlyStateRoots_UpdateStateRootAtIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WriteOnlyStateRoots_UpdateStateRootAtIndex_Call) RunAndReturn(run func(uint64, bytes.B32) error) *WriteOnlyStateRoots_UpdateStateRootAtIndex_Call {
	_c.Call.Return(run)
	return _c
}

// NewWriteOnlyStateRoots creates a new instance of WriteOnlyStateRoots. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriteOnlyStateRoots(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriteOnlyStateRoots {
	mock := &WriteOnlyStateRoots{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
