// Code generated by fastssz. DO NOT EDIT.
// Hash: 065b13fa900a35a9af75fc7abe8894fcfcbd98fc1d4e1f7a307fac9744c0b96e
package state

import (
	"github.com/berachain/beacon-kit/primitives"
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the BeaconStateDeneb object
func (b *BeaconStateDeneb) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BeaconStateDeneb object to a target array
func (b *BeaconStateDeneb) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(b.Slot))

	// Field (1) 'PrevRandaoMix'
	dst = append(dst, b.PrevRandaoMix[:]...)

	// Field (2) 'PrevBlockRoot'
	dst = append(dst, b.PrevBlockRoot[:]...)

	// Field (3) 'ExtraData'
	dst = append(dst, b.ExtraData[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the BeaconStateDeneb object
func (b *BeaconStateDeneb) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 104 {
		return ssz.ErrSize
	}

	// Field (0) 'Slot'
	b.Slot = primitives.Slot(ssz.UnmarshallUint64(buf[0:8]))

	// Field (1) 'PrevRandaoMix'
	copy(b.PrevRandaoMix[:], buf[8:40])

	// Field (2) 'PrevBlockRoot'
	copy(b.PrevBlockRoot[:], buf[40:72])

	// Field (3) 'ExtraData'
	copy(b.ExtraData[:], buf[72:104])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BeaconStateDeneb object
func (b *BeaconStateDeneb) SizeSSZ() (size int) {
	size = 104
	return
}

// HashTreeRoot ssz hashes the BeaconStateDeneb object
func (b *BeaconStateDeneb) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BeaconStateDeneb object with a hasher
func (b *BeaconStateDeneb) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(uint64(b.Slot))

	// Field (1) 'PrevRandaoMix'
	hh.PutBytes(b.PrevRandaoMix[:])

	// Field (2) 'PrevBlockRoot'
	hh.PutBytes(b.PrevBlockRoot[:])

	// Field (3) 'ExtraData'
	hh.PutBytes(b.ExtraData[:])

	if ssz.EnableVectorizedHTR {
		hh.MerkleizeVectorizedHTR(indx)
	} else {
		hh.Merkleize(indx)
	}
	return
}
