# SPDX-License-Identifier: MIT
#
# Copyright (c) 2024 Berachain Foundation
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}.mock.go"
outpkg: "mocks"
resolve-type-alias: False # see https://vektra.github.io/mockery/latest/deprecations/#resolve-type-alias
issue-845-fix: True # see https://vektra.github.io/mockery/latest/deprecations/#issue-845-fix
packages:
  github.com/berachain/beacon-kit/mod/execution/client/ethclient:
    config:
      recursive: True
      with-expecter: true
      include-regex: GethRPCClient
  github.com/berachain/beacon-kit/mod/node-api/backend:
    config:
      recursive: True
      with-expecter: true
      all: True
  github.com/berachain/beacon-kit/mod/node-core/services/registry:
    config:
      recursive: True
      with-expecter: true
      all: True
  github.com/berachain/beacon-kit/mod/storage/interfaces:
    config:
      recursive: False
      with-expecter: true
      all: True
  github.com/berachain/beacon-kit/mod/consensus-types/types:
    config:
      recursive: False
      with-expecter: true
      all: True
  github.com/berachain/beacon-kit/mod/storage/pruner:
    config:
      recursive: False
      with-expecter: true
      all: True
  github.com/berachain/beacon-kit/mod/primitives/crypto:
    config:
      recursive: False
      with-expecter: true
      all: True
  github.com/berachain/beacon-kit/mod/engine-primitives/engine-primitives:
    config:
      recursive: False
      with-expecter: true
      all: True
  github.com/berachain/beacon-kit/mod/state-transition/core:
    config:
      recursive: False
      with-expecter: true
      include-regex: ExecutionEngine
