package types

type BackendHandlers interface {
	GetGenesis()
	GetStateHashTreeRoot(stateId string)
	GetStateFork(stateId string)
	GetStateFinalityCheckpoints(stateId string)
	GetStateValidators(stateId string, id []string, status []string)
	GetStateValidator(stateId string, validatorId string)
	// GetStateValidatorBalances(res http.ResponseWriter, req *http.Request)
	// PostStateValidatorBalances(res http.ResponseWriter, req *http.Request)
	// GetStateCommittees(res http.ResponseWriter, req *http.Request)
	// GetStateSyncCommittees(res http.ResponseWriter, req *http.Request)
	// GetStateRandao(res http.ResponseWriter, req *http.Request)
	// GetBlockHeaders(res http.ResponseWriter, req *http.Request)
	// GetBlockHeader(res http.ResponseWriter, req *http.Request)
	// PostSignedBlindBlockV1(res http.ResponseWriter, req *http.Request)
	// PostSignedBlindBlockV2(res http.ResponseWriter, req *http.Request)
	// PostSignedBlockV1(res http.ResponseWriter, req *http.Request)
	// PostSignedBlockV2(res http.ResponseWriter, req *http.Request)
	// GetBlock(res http.ResponseWriter, req *http.Request)
	// GetBlockRoot(res http.ResponseWriter, req *http.Request)
	// GetStateAttestations(res http.ResponseWriter, req *http.Request)
	// GetBlobSidecars(res http.ResponseWriter, req *http.Request)
	// GetSyncCommiteeAwards(res http.ResponseWriter, req *http.Request)
	// GetDepositSnapshot(res http.ResponseWriter, req *http.Request)
	// GetBlockAwards(res http.ResponseWriter, req *http.Request)
	// GetAttestationRewards(res http.ResponseWriter, req *http.Request)
	// GetBlindedBlock(res http.ResponseWriter, req *http.Request)
	// GetLightClientBootstrapForRoot(res http.ResponseWriter, req *http.Request)
	// GetLightClientUpdateForPeriod(res http.ResponseWriter, req *http.Request)
	// GetLightClientFinalityUpdate(res http.ResponseWriter, req *http.Request)
	// GetLightClientOptimisticUpdate(res http.ResponseWriter, req *http.Request)
	// GetPoolAttestations(res http.ResponseWriter, req *http.Request)
	// PostPoolAttestations(res http.ResponseWriter, req *http.Request)
	// GetPoolAttesterSlashings(res http.ResponseWriter, req *http.Request)
	// PostPoolAttesterSlashings(res http.ResponseWriter, req *http.Request)
	// GetPoolProposerSlashings(res http.ResponseWriter, req *http.Request)
	// PostPoolProposerSlashings(res http.ResponseWriter, req *http.Request)
	// PostPoolSyncCommitteeSignature(res http.ResponseWriter, req *http.Request)
	// GetPoolVoluntaryExits(res http.ResponseWriter, req *http.Request)
	// PostPoolVoluntaryExits(res http.ResponseWriter, req *http.Request)
	// GetPoolSignedBLSExecutionChanges(res http.ResponseWriter, req *http.Request)
	// PostPoolSignedBLSExecutionChanges(res http.ResponseWriter, req *http.Request)
 GetBlockProposerDuties(epoch string)
 SubscribeEvents(topics []string)
 GetSpecConfig()
}
