package types

type BackendHandlers interface {
	GetGenesis()
	GetStateHashTreeRoot(stateId string)
	GetStateFork(stateId string)
	GetStateFinalityCheckpoints(stateId string)
	GetStateValidators(stateId string, id []string, status []string)
	GetStateValidator(stateId string, validatorId string)
	GetStateValidatorBalances(stateId string, id []string)
	PostStateValidatorBalances(stateId string)
	GetStateCommittees(stateId string, epoch string, index string, slot string)
	GetStateSyncCommittees(stateId string, epoch string)
	GetStateRandao(stateId string, epoch string)
	GetBlockHeaders(slot string, parentRoot string)
	GetBlockHeader(blockId string)
	GetBlock(blockId string)
	GetBlockRoot(blockId string)
	GetBlockAttestations(blockId string)
	GetBlobSidecars(blockId string, indices []string)
	GetSyncCommiteeAwards(blockId string)
	GetDepositSnapshot()
	GetBlockAwards(blockId string)
	GetAttestationRewards(epoch string, ids []string)
	GetBlindedBlock(blockId string)
	GetPoolAttestations(slot string, committee_index string)
	PostPoolAttestations(thisoneisfucked string)
	PostPoolSyncCommitteeSignature()
	GetPoolVoluntaryExits()
	PostPoolVoluntaryExits()
	GetPoolSignedBLSExecutionChanges()
	PostPoolSignedBLSExecutionChanges()
	GetBlockProposerDuties(epoch string)
	SubscribeEvents(topics []string)
	GetSpecConfig()
}
