{
 "title": "IVM Beacon Kit Dashboards",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Block for proposal duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(beacon_kit_validator_request_block_for_proposal_duration{quantile=\"0.9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Root Computation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(beacon_kit_validator_state_root_computation_duration)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NewPayload MegaGas/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(reth_engine_rpc_new_payload_gas_per_second) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NewPayload Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(beacon_kit_execution_client_new_payload_duration)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Root Verification Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(beacon_kit_blockchain_state_root_verification_duration)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus block height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"cl-validator-beaconkit-1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cometbft_consensus_validator_last_signed_height{job=\"cl-validator-beaconkit-1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}