{
 "title": "reth",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reth_network_connected_peers", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Highest block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "reth_blockchain_tree_canonical_chain_height",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Headers: Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_unexpected_errors",
     "legendFormat": "Unexpected errors {{pod}}"
    },
    {
     "expr": "reth_downloaders_headers_validation_errors",
     "legendFormat": "Validation errors {{pod}}"
    },
    {
     "expr": "reth_downloaders_headers_timeout_errors",
     "legendFormat": "Timeout errors {{pod}}"
    }
   ]
  },
  {
   "title": "Headers: Downloaded headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_total_downloaded",
     "legendFormat": "Downloaded headers {{pod}}"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_downloaded[$__rate_interval])",
     "legendFormat": "Headers/s {{pod}}"
    }
   ]
  },
  {
   "title": "Sync progress",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 9 },
   "targets": [
    { "expr": "reth_sync_checkpoint", "legendFormat": "{{stage}} {{pod}}" }
   ]
  },
  {
   "title": "Bodies: Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_unexpected_errors",
     "legendFormat": "Unexpected errors {{pod}}"
    },
    {
     "expr": "reth_downloaders_bodies_validation_errors",
     "legendFormat": "Validation errors {{pod}}"
    },
    {
     "expr": "reth_downloaders_bodies_timeout_errors",
     "legendFormat": "Timeout errors {{pod}}"
    }
   ]
  },
  {
   "title": "Headers: Downloaded bodies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_total_downloaded",
     "legendFormat": "Downloaded bodies"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_downloaded[$__rate_interval])",
     "legendFormat": "Bodies/s"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Discovery: Tracked peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    { "expr": "reth_network_tracked_peers", "legendFormat": "Tracked peers {{ pod }}" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "reth_network_outgoing_connections",
     "legendFormat": "Outgoing connections {{pod}}"
    },
    {
     "expr": "reth_network_incoming_connections",
     "legendFormat": "Incoming connections {{pod}}"
    },
    { "expr": "reth_network_connected_peers", "legendFormat": "Connected peers {{pod}}" }
   ]
  },
  {
   "title": "P2P errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "reth_p2pstream_disconnected_errors",
     "legendFormat": "P2P stream disconnected {{pod}}"
    },
    {
     "expr": "reth_network_pending_session_failures",
     "legendFormat": "Failed pending sessions {{pod}}"
    },
    {
     "expr": "reth_network_invalid_messages_received",
     "legendFormat": "Invalid messages {{pod}}"
    }
   ]
  }
 ]
}