# This testnet is run by CI, and attempts to cover a broad range of
# functionality with a single network.

ipv6 = true
vote_extensions_update_height = -1
vote_extensions_enable_height = 0
evidence = 5
prepare_proposal_delay = "100ms"
process_proposal_delay = "100ms"
check_tx_delay = "0ms"
# The most common case (e.g. Cosmos SDK-based chains).
abci_protocol = "builtin"
prometheus = true
peer_gossip_intraloop_sleep_duration = "50ms"
abci_tests_enabled = true

[validators]
validator01 = 1
validator02 = 1
validator03 = 1
validator04 = 1
validator05 = 1

[node.seed01]
mode = "seed"
perturb = ["restart"]

[node.validator01]
seeds = ["seed01"]
snapshot_interval = 3
perturb = ["disconnect"]
clock_skew = "20s"

[node.validator02]
seeds = ["seed01"]
database = "goleveldb"
persist_interval = 0
perturb = ["restart"]

[node.validator03]
seeds = ["seed01"]
persist_interval = 3
retain_blocks = 20
enable_companion_pruning = true
perturb = ["kill"]

[node.validator04]
persistent_peers = ["validator01"]
database = "pebbledb"
perturb = ["pause"]

[node.validator05]
start_at = 5 # Becomes part of the validator set at 5
persistent_peers = ["validator01", "full01"]
database = "pebbledb"
perturb = ["kill", "pause", "disconnect", "restart"]

[node.full01]
start_at = 10
mode = "full"
persistent_peers = ["validator01", "validator02", "validator03", "validator04", "validator05"]
retain_blocks = 20
enable_companion_pruning = true
perturb = ["restart"]

[node.full02]
start_at = 15
mode = "full"
seeds = ["seed01"]
perturb = ["restart"]
