// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: runtime/modules/beacon/v1alpha1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DepositQueueLengthResponse is the response message for the DepositQueueLength RPC.
// It contains the length of the deposit queue, indicating how many deposits are
// currently waiting to be processed.
type DepositQueueLengthResponse struct {
	// length represents the number of deposits in the queue.
	Length uint64 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (m *DepositQueueLengthResponse) Reset()         { *m = DepositQueueLengthResponse{} }
func (m *DepositQueueLengthResponse) String() string { return proto.CompactTextString(m) }
func (*DepositQueueLengthResponse) ProtoMessage()    {}
func (*DepositQueueLengthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c1460636d2f34b, []int{0}
}
func (m *DepositQueueLengthResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DepositQueueLengthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DepositQueueLengthResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DepositQueueLengthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositQueueLengthResponse.Merge(m, src)
}
func (m *DepositQueueLengthResponse) XXX_Size() int {
	return m.Size()
}
func (m *DepositQueueLengthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositQueueLengthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositQueueLengthResponse proto.InternalMessageInfo

func (m *DepositQueueLengthResponse) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func init() {
	proto.RegisterType((*DepositQueueLengthResponse)(nil), "runtime.modules.beacon.v1alpha1.DepositQueueLengthResponse")
}

func init() {
	proto.RegisterFile("runtime/modules/beacon/v1alpha1/query.proto", fileDescriptor_f9c1460636d2f34b)
}

var fileDescriptor_f9c1460636d2f34b = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x31, 0x4b, 0x3b, 0x41,
	0x10, 0xc5, 0xb3, 0x7f, 0xfe, 0xa6, 0xb8, 0xf2, 0x8a, 0x20, 0x17, 0x59, 0x25, 0x20, 0x8a, 0xe2,
	0x2e, 0x89, 0x76, 0x5a, 0x89, 0x76, 0x36, 0x49, 0x61, 0x61, 0x13, 0xf6, 0x2e, 0xe3, 0xdd, 0xe2,
	0xdd, 0xce, 0xe6, 0x76, 0x37, 0x90, 0xd6, 0xca, 0x52, 0xb0, 0xb6, 0xb6, 0xf5, 0x63, 0x58, 0x06,
	0x6c, 0x2c, 0x25, 0x11, 0xfc, 0x1a, 0x92, 0xdc, 0xa6, 0x90, 0x10, 0x2c, 0x67, 0xe7, 0xfd, 0xe6,
	0xbd, 0xd9, 0x09, 0x0e, 0x4b, 0xa7, 0xac, 0x2c, 0x80, 0x17, 0x38, 0x70, 0x39, 0x18, 0x1e, 0x83,
	0x48, 0x50, 0xf1, 0x51, 0x5b, 0xe4, 0x3a, 0x13, 0x6d, 0x3e, 0x74, 0x50, 0x8e, 0x99, 0x2e, 0xd1,
	0x62, 0xb8, 0xed, 0xc5, 0xcc, 0x8b, 0x59, 0x25, 0x66, 0x4b, 0x71, 0xd4, 0x4c, 0xd0, 0x14, 0x68,
	0x2a, 0x88, 0x8f, 0x7e, 0xd1, 0xd1, 0x56, 0x8a, 0x98, 0xe6, 0xc0, 0x85, 0x96, 0x5c, 0x28, 0x85,
	0x56, 0x58, 0x89, 0xca, 0xf8, 0x6e, 0xd3, 0x77, 0x17, 0x55, 0xec, 0x6e, 0x39, 0x14, 0xda, 0x7a,
	0xb4, 0x75, 0x12, 0x44, 0x17, 0xa0, 0xd1, 0x48, 0xdb, 0x75, 0xe0, 0xe0, 0x0a, 0x54, 0x6a, 0xb3,
	0x1e, 0x18, 0x8d, 0xca, 0x40, 0xd8, 0x08, 0xea, 0xf9, 0xe2, 0x65, 0x93, 0xec, 0x90, 0xfd, 0xff,
	0x3d, 0x5f, 0x75, 0x5e, 0x48, 0xb0, 0xd1, 0x9d, 0x07, 0x08, 0x9f, 0x49, 0x10, 0xae, 0x0e, 0x08,
	0x1b, 0xac, 0x32, 0x65, 0x4b, 0x53, 0x76, 0x39, 0x37, 0x8d, 0x4e, 0xd9, 0x1f, 0x8b, 0xb2, 0xf5,
	0x69, 0x5a, 0x9d, 0x87, 0xef, 0xd7, 0x03, 0x72, 0xff, 0xfe, 0xf5, 0xf4, 0x6f, 0x2f, 0xdc, 0x5d,
	0xf9, 0xcf, 0x41, 0x45, 0xf6, 0x87, 0x73, 0xb4, 0x5f, 0x25, 0x3d, 0xbf, 0x7e, 0x9b, 0x52, 0x32,
	0x99, 0x52, 0xf2, 0x39, 0xa5, 0xe4, 0x71, 0x46, 0x6b, 0x93, 0x19, 0xad, 0x7d, 0xcc, 0x68, 0xed,
	0xe6, 0x2c, 0x95, 0x36, 0x73, 0x31, 0x4b, 0xb0, 0xe0, 0x31, 0x94, 0x22, 0xc9, 0x84, 0x54, 0x7e,
	0xe8, 0xd1, 0x9d, 0xb4, 0x7c, 0xcd, 0xfd, 0xec, 0x58, 0x83, 0x89, 0xeb, 0x8b, 0xc5, 0x8e, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x53, 0xbc, 0x65, 0x5f, 0xe6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Validators queries all validators that match the given status.
	//
	// When called from another module, this query might consume a high amount of
	// gas if the pagination field is incorrectly set.
	DepositQueueLength(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DepositQueueLengthResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DepositQueueLength(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DepositQueueLengthResponse, error) {
	out := new(DepositQueueLengthResponse)
	err := c.cc.Invoke(ctx, "/runtime.modules.beacon.v1alpha1.Query/DepositQueueLength", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Validators queries all validators that match the given status.
	//
	// When called from another module, this query might consume a high amount of
	// gas if the pagination field is incorrectly set.
	DepositQueueLength(context.Context, *emptypb.Empty) (*DepositQueueLengthResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) DepositQueueLength(ctx context.Context, req *emptypb.Empty) (*DepositQueueLengthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositQueueLength not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_DepositQueueLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DepositQueueLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.modules.beacon.v1alpha1.Query/DepositQueueLength",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DepositQueueLength(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.modules.beacon.v1alpha1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepositQueueLength",
			Handler:    _Query_DepositQueueLength_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime/modules/beacon/v1alpha1/query.proto",
}

func (m *DepositQueueLengthResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DepositQueueLengthResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DepositQueueLengthResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Length != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Length))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DepositQueueLengthResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Length != 0 {
		n += 1 + sovQuery(uint64(m.Length))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DepositQueueLengthResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DepositQueueLengthResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DepositQueueLengthResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Length", wireType)
			}
			m.Length = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Length |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
