// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: runtime/modules/beacon/v1alpha1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BeaconKitBlockContainer is a container for beacon block.
type BeaconKitBlockContainer struct {
	// // block is the beacon block.
	// oneof block {}
	SszBlockBytes []byte `protobuf:"bytes,1,opt,name=ssz_block_bytes,json=sszBlockBytes,proto3" json:"ssz_block_bytes,omitempty"`
}

func (m *BeaconKitBlockContainer) Reset()         { *m = BeaconKitBlockContainer{} }
func (m *BeaconKitBlockContainer) String() string { return proto.CompactTextString(m) }
func (*BeaconKitBlockContainer) ProtoMessage()    {}
func (*BeaconKitBlockContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab196e01bb8f6639, []int{0}
}
func (m *BeaconKitBlockContainer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BeaconKitBlockContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BeaconKitBlockContainer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BeaconKitBlockContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconKitBlockContainer.Merge(m, src)
}
func (m *BeaconKitBlockContainer) XXX_Size() int {
	return m.Size()
}
func (m *BeaconKitBlockContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconKitBlockContainer.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconKitBlockContainer proto.InternalMessageInfo

func (m *BeaconKitBlockContainer) GetSszBlockBytes() []byte {
	if m != nil {
		return m.SszBlockBytes
	}
	return nil
}

// BeaconKitBlockContainerResp is a container for beacon block response.
type ProcessBeaconBlockResponse struct {
}

func (m *ProcessBeaconBlockResponse) Reset()         { *m = ProcessBeaconBlockResponse{} }
func (m *ProcessBeaconBlockResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessBeaconBlockResponse) ProtoMessage()    {}
func (*ProcessBeaconBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab196e01bb8f6639, []int{1}
}
func (m *ProcessBeaconBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProcessBeaconBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProcessBeaconBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProcessBeaconBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessBeaconBlockResponse.Merge(m, src)
}
func (m *ProcessBeaconBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *ProcessBeaconBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessBeaconBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessBeaconBlockResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BeaconKitBlockContainer)(nil), "runtime.modules.beacon.v1alpha1.BeaconKitBlockContainer")
	proto.RegisterType((*ProcessBeaconBlockResponse)(nil), "runtime.modules.beacon.v1alpha1.ProcessBeaconBlockResponse")
}

func init() {
	proto.RegisterFile("runtime/modules/beacon/v1alpha1/tx.proto", fileDescriptor_ab196e01bb8f6639)
}

var fileDescriptor_ab196e01bb8f6639 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd1, 0x31, 0x4b, 0xc4, 0x30,
	0x14, 0x07, 0xf0, 0x0b, 0xa2, 0x43, 0x50, 0x84, 0x2e, 0x27, 0x45, 0xa2, 0xdc, 0x20, 0x87, 0x43,
	0x42, 0x75, 0x11, 0x9d, 0xac, 0xa3, 0x08, 0x72, 0x38, 0xb9, 0x1c, 0x49, 0x2f, 0xf4, 0x82, 0x6d,
	0x5f, 0xc9, 0x4b, 0x8b, 0x77, 0x93, 0xbb, 0x8b, 0xb3, 0x9f, 0xc2, 0x8f, 0xe1, 0x78, 0xa3, 0xa3,
	0xb4, 0x83, 0x5f, 0x43, 0xda, 0x9e, 0x93, 0x94, 0x9b, 0x02, 0x2f, 0xbf, 0x7f, 0xf8, 0x93, 0x47,
	0xc7, 0xb6, 0xc8, 0x9c, 0x49, 0xb5, 0x48, 0x61, 0x56, 0x24, 0x1a, 0x85, 0xd2, 0x32, 0x82, 0x4c,
	0x94, 0x81, 0x4c, 0xf2, 0xb9, 0x0c, 0x84, 0x7b, 0xe6, 0xb9, 0x05, 0x07, 0xde, 0xd1, 0x5a, 0xf2,
	0xb5, 0xe4, 0x9d, 0xe4, 0x7f, 0xd2, 0x1f, 0x46, 0x80, 0x29, 0xa0, 0x48, 0x31, 0x16, 0x65, 0xd0,
	0x1c, 0x5d, 0x72, 0x74, 0x4d, 0x87, 0x61, 0x6b, 0x6f, 0x8d, 0x0b, 0x13, 0x88, 0x9e, 0x6e, 0x20,
	0x73, 0xd2, 0x64, 0xda, 0x7a, 0x27, 0x74, 0x1f, 0x71, 0x39, 0x55, 0xcd, 0x74, 0xaa, 0x16, 0x4e,
	0xe3, 0x01, 0x39, 0x26, 0xe3, 0xdd, 0xc9, 0x1e, 0xe2, 0xb2, 0xb5, 0x61, 0x33, 0x1c, 0x1d, 0x52,
	0xff, 0xde, 0x42, 0xa4, 0x11, 0xbb, 0x97, 0xda, 0xab, 0x89, 0xc6, 0x1c, 0x32, 0xd4, 0x67, 0xef,
	0x84, 0x6e, 0xdd, 0x61, 0xec, 0xbd, 0x12, 0xea, 0xfd, 0x67, 0xde, 0x05, 0xdf, 0x50, 0x9d, 0xf7,
	0xd4, 0xf3, 0xaf, 0x36, 0x26, 0xfb, 0x5b, 0xf9, 0xdb, 0x2f, 0x3f, 0x1f, 0xa7, 0x24, 0x7c, 0xf8,
	0xac, 0x18, 0x59, 0x55, 0x8c, 0x7c, 0x57, 0x8c, 0xbc, 0xd5, 0x6c, 0xb0, 0xaa, 0xd9, 0xe0, 0xab,
	0x66, 0x83, 0xc7, 0xcb, 0xd8, 0xb8, 0x79, 0xa1, 0x78, 0x04, 0xa9, 0x30, 0x0e, 0x67, 0xba, 0x54,
	0x5a, 0x5a, 0xa1, 0x20, 0x91, 0xd6, 0xa0, 0xe8, 0xd9, 0x8c, 0x5b, 0xe4, 0x1a, 0xd5, 0x4e, 0xfb,
	0xb5, 0xe7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xbf, 0x06, 0x4b, 0xc0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Send defines a method for sending coins from one account to another account.
	ProcessBeaconBlock(ctx context.Context, in *BeaconKitBlockContainer, opts ...grpc.CallOption) (*ProcessBeaconBlockResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ProcessBeaconBlock(ctx context.Context, in *BeaconKitBlockContainer, opts ...grpc.CallOption) (*ProcessBeaconBlockResponse, error) {
	out := new(ProcessBeaconBlockResponse)
	err := c.cc.Invoke(ctx, "/runtime.modules.beacon.v1alpha1.Msg/ProcessBeaconBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Send defines a method for sending coins from one account to another account.
	ProcessBeaconBlock(context.Context, *BeaconKitBlockContainer) (*ProcessBeaconBlockResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ProcessBeaconBlock(ctx context.Context, req *BeaconKitBlockContainer) (*ProcessBeaconBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBeaconBlock not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ProcessBeaconBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconKitBlockContainer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProcessBeaconBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.modules.beacon.v1alpha1.Msg/ProcessBeaconBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProcessBeaconBlock(ctx, req.(*BeaconKitBlockContainer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.modules.beacon.v1alpha1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessBeaconBlock",
			Handler:    _Msg_ProcessBeaconBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime/modules/beacon/v1alpha1/tx.proto",
}

func (m *BeaconKitBlockContainer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BeaconKitBlockContainer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BeaconKitBlockContainer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SszBlockBytes) > 0 {
		i -= len(m.SszBlockBytes)
		copy(dAtA[i:], m.SszBlockBytes)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SszBlockBytes)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProcessBeaconBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProcessBeaconBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProcessBeaconBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BeaconKitBlockContainer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SszBlockBytes)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *ProcessBeaconBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BeaconKitBlockContainer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BeaconKitBlockContainer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BeaconKitBlockContainer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SszBlockBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SszBlockBytes = append(m.SszBlockBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.SszBlockBytes == nil {
				m.SszBlockBytes = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProcessBeaconBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProcessBeaconBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProcessBeaconBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
