// SPDX-License-Identifier: MIT
//
// Copyright (c) 2024 Berachain Foundation
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: types/consensus/v1/container.proto

package consensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BeaconKitBlockContainer is a container for beacon block.
type BeaconKitBlockContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BeaconKitBlockContainer) Reset() {
	*x = BeaconKitBlockContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_consensus_v1_container_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconKitBlockContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconKitBlockContainer) ProtoMessage() {}

func (x *BeaconKitBlockContainer) ProtoReflect() protoreflect.Message {
	mi := &file_types_consensus_v1_container_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconKitBlockContainer.ProtoReflect.Descriptor instead.
func (*BeaconKitBlockContainer) Descriptor() ([]byte, []int) {
	return file_types_consensus_v1_container_proto_rawDescGZIP(), []int{0}
}

var File_types_consensus_v1_container_proto protoreflect.FileDescriptor

var file_types_consensus_v1_container_proto_rawDesc = []byte{
	0x0a, 0x22, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x19, 0x0a, 0x17, 0x42, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x4b, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x74, 0x73, 0x64, 0x65, 0x76, 0x62, 0x65, 0x61, 0x72, 0x2f, 0x62, 0x6f, 0x6c,
	0x61, 0x72, 0x69, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65,
	0x6e, 0x73, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75,
	0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_consensus_v1_container_proto_rawDescOnce sync.Once
	file_types_consensus_v1_container_proto_rawDescData = file_types_consensus_v1_container_proto_rawDesc
)

func file_types_consensus_v1_container_proto_rawDescGZIP() []byte {
	file_types_consensus_v1_container_proto_rawDescOnce.Do(func() {
		file_types_consensus_v1_container_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_consensus_v1_container_proto_rawDescData)
	})
	return file_types_consensus_v1_container_proto_rawDescData
}

var file_types_consensus_v1_container_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_consensus_v1_container_proto_goTypes = []interface{}{
	(*BeaconKitBlockContainer)(nil), // 0: types.consensus.v1.BeaconKitBlockContainer
}
var file_types_consensus_v1_container_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_consensus_v1_container_proto_init() }
func file_types_consensus_v1_container_proto_init() {
	if File_types_consensus_v1_container_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_consensus_v1_container_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconKitBlockContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_consensus_v1_container_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_consensus_v1_container_proto_goTypes,
		DependencyIndexes: file_types_consensus_v1_container_proto_depIdxs,
		MessageInfos:      file_types_consensus_v1_container_proto_msgTypes,
	}.Build()
	File_types_consensus_v1_container_proto = out.File
	file_types_consensus_v1_container_proto_rawDesc = nil
	file_types_consensus_v1_container_proto_goTypes = nil
	file_types_consensus_v1_container_proto_depIdxs = nil
}
