// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	bytes "github.com/berachain/beacon-kit/mod/primitives/pkg/bytes"
	common "github.com/ethereum/go-ethereum/common"

	math "github.com/berachain/beacon-kit/mod/primitives/pkg/math"

	mock "github.com/stretchr/testify/mock"
)

// InnerExecutionPayloadHeader is an autogenerated mock type for the InnerExecutionPayloadHeader type
type InnerExecutionPayloadHeader struct {
	mock.Mock
}

type InnerExecutionPayloadHeader_Expecter struct {
	mock *mock.Mock
}

func (_m *InnerExecutionPayloadHeader) EXPECT() *InnerExecutionPayloadHeader_Expecter {
	return &InnerExecutionPayloadHeader_Expecter{mock: &_m.Mock}
}

// GetBaseFeePerGas provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetBaseFeePerGas() math.U256L {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBaseFeePerGas")
	}

	var r0 math.U256L
	if rf, ok := ret.Get(0).(func() math.U256L); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(math.U256L)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetBaseFeePerGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBaseFeePerGas'
type InnerExecutionPayloadHeader_GetBaseFeePerGas_Call struct {
	*mock.Call
}

// GetBaseFeePerGas is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetBaseFeePerGas() *InnerExecutionPayloadHeader_GetBaseFeePerGas_Call {
	return &InnerExecutionPayloadHeader_GetBaseFeePerGas_Call{Call: _e.mock.On("GetBaseFeePerGas")}
}

func (_c *InnerExecutionPayloadHeader_GetBaseFeePerGas_Call) Run(run func()) *InnerExecutionPayloadHeader_GetBaseFeePerGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetBaseFeePerGas_Call) Return(_a0 math.U256L) *InnerExecutionPayloadHeader_GetBaseFeePerGas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetBaseFeePerGas_Call) RunAndReturn(run func() math.U256L) *InnerExecutionPayloadHeader_GetBaseFeePerGas_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlobGasUsed provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetBlobGasUsed() math.U64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBlobGasUsed")
	}

	var r0 math.U64
	if rf, ok := ret.Get(0).(func() math.U64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(math.U64)
	}

	return r0
}

// InnerExecutionPayloadHeader_GetBlobGasUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlobGasUsed'
type InnerExecutionPayloadHeader_GetBlobGasUsed_Call struct {
	*mock.Call
}

// GetBlobGasUsed is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetBlobGasUsed() *InnerExecutionPayloadHeader_GetBlobGasUsed_Call {
	return &InnerExecutionPayloadHeader_GetBlobGasUsed_Call{Call: _e.mock.On("GetBlobGasUsed")}
}

func (_c *InnerExecutionPayloadHeader_GetBlobGasUsed_Call) Run(run func()) *InnerExecutionPayloadHeader_GetBlobGasUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetBlobGasUsed_Call) Return(_a0 math.U64) *InnerExecutionPayloadHeader_GetBlobGasUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetBlobGasUsed_Call) RunAndReturn(run func() math.U64) *InnerExecutionPayloadHeader_GetBlobGasUsed_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockHash provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetBlockHash() common.Hash {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBlockHash")
	}

	var r0 common.Hash
	if rf, ok := ret.Get(0).(func() common.Hash); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetBlockHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockHash'
type InnerExecutionPayloadHeader_GetBlockHash_Call struct {
	*mock.Call
}

// GetBlockHash is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetBlockHash() *InnerExecutionPayloadHeader_GetBlockHash_Call {
	return &InnerExecutionPayloadHeader_GetBlockHash_Call{Call: _e.mock.On("GetBlockHash")}
}

func (_c *InnerExecutionPayloadHeader_GetBlockHash_Call) Run(run func()) *InnerExecutionPayloadHeader_GetBlockHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetBlockHash_Call) Return(_a0 common.Hash) *InnerExecutionPayloadHeader_GetBlockHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetBlockHash_Call) RunAndReturn(run func() common.Hash) *InnerExecutionPayloadHeader_GetBlockHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetExcessBlobGas provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetExcessBlobGas() math.U64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExcessBlobGas")
	}

	var r0 math.U64
	if rf, ok := ret.Get(0).(func() math.U64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(math.U64)
	}

	return r0
}

// InnerExecutionPayloadHeader_GetExcessBlobGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExcessBlobGas'
type InnerExecutionPayloadHeader_GetExcessBlobGas_Call struct {
	*mock.Call
}

// GetExcessBlobGas is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetExcessBlobGas() *InnerExecutionPayloadHeader_GetExcessBlobGas_Call {
	return &InnerExecutionPayloadHeader_GetExcessBlobGas_Call{Call: _e.mock.On("GetExcessBlobGas")}
}

func (_c *InnerExecutionPayloadHeader_GetExcessBlobGas_Call) Run(run func()) *InnerExecutionPayloadHeader_GetExcessBlobGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetExcessBlobGas_Call) Return(_a0 math.U64) *InnerExecutionPayloadHeader_GetExcessBlobGas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetExcessBlobGas_Call) RunAndReturn(run func() math.U64) *InnerExecutionPayloadHeader_GetExcessBlobGas_Call {
	_c.Call.Return(run)
	return _c
}

// GetExtraData provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetExtraData() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExtraData")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetExtraData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExtraData'
type InnerExecutionPayloadHeader_GetExtraData_Call struct {
	*mock.Call
}

// GetExtraData is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetExtraData() *InnerExecutionPayloadHeader_GetExtraData_Call {
	return &InnerExecutionPayloadHeader_GetExtraData_Call{Call: _e.mock.On("GetExtraData")}
}

func (_c *InnerExecutionPayloadHeader_GetExtraData_Call) Run(run func()) *InnerExecutionPayloadHeader_GetExtraData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetExtraData_Call) Return(_a0 []byte) *InnerExecutionPayloadHeader_GetExtraData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetExtraData_Call) RunAndReturn(run func() []byte) *InnerExecutionPayloadHeader_GetExtraData_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeeRecipient provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetFeeRecipient() common.Address {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFeeRecipient")
	}

	var r0 common.Address
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetFeeRecipient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeeRecipient'
type InnerExecutionPayloadHeader_GetFeeRecipient_Call struct {
	*mock.Call
}

// GetFeeRecipient is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetFeeRecipient() *InnerExecutionPayloadHeader_GetFeeRecipient_Call {
	return &InnerExecutionPayloadHeader_GetFeeRecipient_Call{Call: _e.mock.On("GetFeeRecipient")}
}

func (_c *InnerExecutionPayloadHeader_GetFeeRecipient_Call) Run(run func()) *InnerExecutionPayloadHeader_GetFeeRecipient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetFeeRecipient_Call) Return(_a0 common.Address) *InnerExecutionPayloadHeader_GetFeeRecipient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetFeeRecipient_Call) RunAndReturn(run func() common.Address) *InnerExecutionPayloadHeader_GetFeeRecipient_Call {
	_c.Call.Return(run)
	return _c
}

// GetGasLimit provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetGasLimit() math.U64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGasLimit")
	}

	var r0 math.U64
	if rf, ok := ret.Get(0).(func() math.U64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(math.U64)
	}

	return r0
}

// InnerExecutionPayloadHeader_GetGasLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGasLimit'
type InnerExecutionPayloadHeader_GetGasLimit_Call struct {
	*mock.Call
}

// GetGasLimit is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetGasLimit() *InnerExecutionPayloadHeader_GetGasLimit_Call {
	return &InnerExecutionPayloadHeader_GetGasLimit_Call{Call: _e.mock.On("GetGasLimit")}
}

func (_c *InnerExecutionPayloadHeader_GetGasLimit_Call) Run(run func()) *InnerExecutionPayloadHeader_GetGasLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetGasLimit_Call) Return(_a0 math.U64) *InnerExecutionPayloadHeader_GetGasLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetGasLimit_Call) RunAndReturn(run func() math.U64) *InnerExecutionPayloadHeader_GetGasLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetGasUsed provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetGasUsed() math.U64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGasUsed")
	}

	var r0 math.U64
	if rf, ok := ret.Get(0).(func() math.U64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(math.U64)
	}

	return r0
}

// InnerExecutionPayloadHeader_GetGasUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGasUsed'
type InnerExecutionPayloadHeader_GetGasUsed_Call struct {
	*mock.Call
}

// GetGasUsed is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetGasUsed() *InnerExecutionPayloadHeader_GetGasUsed_Call {
	return &InnerExecutionPayloadHeader_GetGasUsed_Call{Call: _e.mock.On("GetGasUsed")}
}

func (_c *InnerExecutionPayloadHeader_GetGasUsed_Call) Run(run func()) *InnerExecutionPayloadHeader_GetGasUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetGasUsed_Call) Return(_a0 math.U64) *InnerExecutionPayloadHeader_GetGasUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetGasUsed_Call) RunAndReturn(run func() math.U64) *InnerExecutionPayloadHeader_GetGasUsed_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogsBloom provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetLogsBloom() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogsBloom")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetLogsBloom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogsBloom'
type InnerExecutionPayloadHeader_GetLogsBloom_Call struct {
	*mock.Call
}

// GetLogsBloom is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetLogsBloom() *InnerExecutionPayloadHeader_GetLogsBloom_Call {
	return &InnerExecutionPayloadHeader_GetLogsBloom_Call{Call: _e.mock.On("GetLogsBloom")}
}

func (_c *InnerExecutionPayloadHeader_GetLogsBloom_Call) Run(run func()) *InnerExecutionPayloadHeader_GetLogsBloom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetLogsBloom_Call) Return(_a0 []byte) *InnerExecutionPayloadHeader_GetLogsBloom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetLogsBloom_Call) RunAndReturn(run func() []byte) *InnerExecutionPayloadHeader_GetLogsBloom_Call {
	_c.Call.Return(run)
	return _c
}

// GetNumber provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetNumber() math.U64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNumber")
	}

	var r0 math.U64
	if rf, ok := ret.Get(0).(func() math.U64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(math.U64)
	}

	return r0
}

// InnerExecutionPayloadHeader_GetNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNumber'
type InnerExecutionPayloadHeader_GetNumber_Call struct {
	*mock.Call
}

// GetNumber is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetNumber() *InnerExecutionPayloadHeader_GetNumber_Call {
	return &InnerExecutionPayloadHeader_GetNumber_Call{Call: _e.mock.On("GetNumber")}
}

func (_c *InnerExecutionPayloadHeader_GetNumber_Call) Run(run func()) *InnerExecutionPayloadHeader_GetNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetNumber_Call) Return(_a0 math.U64) *InnerExecutionPayloadHeader_GetNumber_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetNumber_Call) RunAndReturn(run func() math.U64) *InnerExecutionPayloadHeader_GetNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetParentHash provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetParentHash() common.Hash {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParentHash")
	}

	var r0 common.Hash
	if rf, ok := ret.Get(0).(func() common.Hash); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetParentHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParentHash'
type InnerExecutionPayloadHeader_GetParentHash_Call struct {
	*mock.Call
}

// GetParentHash is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetParentHash() *InnerExecutionPayloadHeader_GetParentHash_Call {
	return &InnerExecutionPayloadHeader_GetParentHash_Call{Call: _e.mock.On("GetParentHash")}
}

func (_c *InnerExecutionPayloadHeader_GetParentHash_Call) Run(run func()) *InnerExecutionPayloadHeader_GetParentHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetParentHash_Call) Return(_a0 common.Hash) *InnerExecutionPayloadHeader_GetParentHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetParentHash_Call) RunAndReturn(run func() common.Hash) *InnerExecutionPayloadHeader_GetParentHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrevRandao provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetPrevRandao() bytes.B32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrevRandao")
	}

	var r0 bytes.B32
	if rf, ok := ret.Get(0).(func() bytes.B32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bytes.B32)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetPrevRandao_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrevRandao'
type InnerExecutionPayloadHeader_GetPrevRandao_Call struct {
	*mock.Call
}

// GetPrevRandao is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetPrevRandao() *InnerExecutionPayloadHeader_GetPrevRandao_Call {
	return &InnerExecutionPayloadHeader_GetPrevRandao_Call{Call: _e.mock.On("GetPrevRandao")}
}

func (_c *InnerExecutionPayloadHeader_GetPrevRandao_Call) Run(run func()) *InnerExecutionPayloadHeader_GetPrevRandao_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetPrevRandao_Call) Return(_a0 bytes.B32) *InnerExecutionPayloadHeader_GetPrevRandao_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetPrevRandao_Call) RunAndReturn(run func() bytes.B32) *InnerExecutionPayloadHeader_GetPrevRandao_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceiptsRoot provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetReceiptsRoot() bytes.B32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetReceiptsRoot")
	}

	var r0 bytes.B32
	if rf, ok := ret.Get(0).(func() bytes.B32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bytes.B32)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetReceiptsRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceiptsRoot'
type InnerExecutionPayloadHeader_GetReceiptsRoot_Call struct {
	*mock.Call
}

// GetReceiptsRoot is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetReceiptsRoot() *InnerExecutionPayloadHeader_GetReceiptsRoot_Call {
	return &InnerExecutionPayloadHeader_GetReceiptsRoot_Call{Call: _e.mock.On("GetReceiptsRoot")}
}

func (_c *InnerExecutionPayloadHeader_GetReceiptsRoot_Call) Run(run func()) *InnerExecutionPayloadHeader_GetReceiptsRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetReceiptsRoot_Call) Return(_a0 bytes.B32) *InnerExecutionPayloadHeader_GetReceiptsRoot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetReceiptsRoot_Call) RunAndReturn(run func() bytes.B32) *InnerExecutionPayloadHeader_GetReceiptsRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateRoot provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetStateRoot() bytes.B32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStateRoot")
	}

	var r0 bytes.B32
	if rf, ok := ret.Get(0).(func() bytes.B32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bytes.B32)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetStateRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateRoot'
type InnerExecutionPayloadHeader_GetStateRoot_Call struct {
	*mock.Call
}

// GetStateRoot is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetStateRoot() *InnerExecutionPayloadHeader_GetStateRoot_Call {
	return &InnerExecutionPayloadHeader_GetStateRoot_Call{Call: _e.mock.On("GetStateRoot")}
}

func (_c *InnerExecutionPayloadHeader_GetStateRoot_Call) Run(run func()) *InnerExecutionPayloadHeader_GetStateRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetStateRoot_Call) Return(_a0 bytes.B32) *InnerExecutionPayloadHeader_GetStateRoot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetStateRoot_Call) RunAndReturn(run func() bytes.B32) *InnerExecutionPayloadHeader_GetStateRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimestamp provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetTimestamp() math.U64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTimestamp")
	}

	var r0 math.U64
	if rf, ok := ret.Get(0).(func() math.U64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(math.U64)
	}

	return r0
}

// InnerExecutionPayloadHeader_GetTimestamp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimestamp'
type InnerExecutionPayloadHeader_GetTimestamp_Call struct {
	*mock.Call
}

// GetTimestamp is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetTimestamp() *InnerExecutionPayloadHeader_GetTimestamp_Call {
	return &InnerExecutionPayloadHeader_GetTimestamp_Call{Call: _e.mock.On("GetTimestamp")}
}

func (_c *InnerExecutionPayloadHeader_GetTimestamp_Call) Run(run func()) *InnerExecutionPayloadHeader_GetTimestamp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetTimestamp_Call) Return(_a0 math.U64) *InnerExecutionPayloadHeader_GetTimestamp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetTimestamp_Call) RunAndReturn(run func() math.U64) *InnerExecutionPayloadHeader_GetTimestamp_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionsRoot provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetTransactionsRoot() bytes.B32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsRoot")
	}

	var r0 bytes.B32
	if rf, ok := ret.Get(0).(func() bytes.B32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bytes.B32)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetTransactionsRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionsRoot'
type InnerExecutionPayloadHeader_GetTransactionsRoot_Call struct {
	*mock.Call
}

// GetTransactionsRoot is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetTransactionsRoot() *InnerExecutionPayloadHeader_GetTransactionsRoot_Call {
	return &InnerExecutionPayloadHeader_GetTransactionsRoot_Call{Call: _e.mock.On("GetTransactionsRoot")}
}

func (_c *InnerExecutionPayloadHeader_GetTransactionsRoot_Call) Run(run func()) *InnerExecutionPayloadHeader_GetTransactionsRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetTransactionsRoot_Call) Return(_a0 bytes.B32) *InnerExecutionPayloadHeader_GetTransactionsRoot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetTransactionsRoot_Call) RunAndReturn(run func() bytes.B32) *InnerExecutionPayloadHeader_GetTransactionsRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawalsRoot provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) GetWithdrawalsRoot() bytes.B32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsRoot")
	}

	var r0 bytes.B32
	if rf, ok := ret.Get(0).(func() bytes.B32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bytes.B32)
		}
	}

	return r0
}

// InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalsRoot'
type InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call struct {
	*mock.Call
}

// GetWithdrawalsRoot is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) GetWithdrawalsRoot() *InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call {
	return &InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call{Call: _e.mock.On("GetWithdrawalsRoot")}
}

func (_c *InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call) Run(run func()) *InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call) Return(_a0 bytes.B32) *InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call) RunAndReturn(run func() bytes.B32) *InnerExecutionPayloadHeader_GetWithdrawalsRoot_Call {
	_c.Call.Return(run)
	return _c
}

// HashTreeRoot provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) HashTreeRoot() ([32]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HashTreeRoot")
	}

	var r0 [32]byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([32]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() [32]byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InnerExecutionPayloadHeader_HashTreeRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashTreeRoot'
type InnerExecutionPayloadHeader_HashTreeRoot_Call struct {
	*mock.Call
}

// HashTreeRoot is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) HashTreeRoot() *InnerExecutionPayloadHeader_HashTreeRoot_Call {
	return &InnerExecutionPayloadHeader_HashTreeRoot_Call{Call: _e.mock.On("HashTreeRoot")}
}

func (_c *InnerExecutionPayloadHeader_HashTreeRoot_Call) Run(run func()) *InnerExecutionPayloadHeader_HashTreeRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_HashTreeRoot_Call) Return(_a0 [32]byte, _a1 error) *InnerExecutionPayloadHeader_HashTreeRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InnerExecutionPayloadHeader_HashTreeRoot_Call) RunAndReturn(run func() ([32]byte, error)) *InnerExecutionPayloadHeader_HashTreeRoot_Call {
	_c.Call.Return(run)
	return _c
}

// IsNil provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) IsNil() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNil")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// InnerExecutionPayloadHeader_IsNil_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNil'
type InnerExecutionPayloadHeader_IsNil_Call struct {
	*mock.Call
}

// IsNil is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) IsNil() *InnerExecutionPayloadHeader_IsNil_Call {
	return &InnerExecutionPayloadHeader_IsNil_Call{Call: _e.mock.On("IsNil")}
}

func (_c *InnerExecutionPayloadHeader_IsNil_Call) Run(run func()) *InnerExecutionPayloadHeader_IsNil_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_IsNil_Call) Return(_a0 bool) *InnerExecutionPayloadHeader_IsNil_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_IsNil_Call) RunAndReturn(run func() bool) *InnerExecutionPayloadHeader_IsNil_Call {
	_c.Call.Return(run)
	return _c
}

// MarshalJSON provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) MarshalJSON() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarshalJSON")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InnerExecutionPayloadHeader_MarshalJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalJSON'
type InnerExecutionPayloadHeader_MarshalJSON_Call struct {
	*mock.Call
}

// MarshalJSON is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) MarshalJSON() *InnerExecutionPayloadHeader_MarshalJSON_Call {
	return &InnerExecutionPayloadHeader_MarshalJSON_Call{Call: _e.mock.On("MarshalJSON")}
}

func (_c *InnerExecutionPayloadHeader_MarshalJSON_Call) Run(run func()) *InnerExecutionPayloadHeader_MarshalJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_MarshalJSON_Call) Return(_a0 []byte, _a1 error) *InnerExecutionPayloadHeader_MarshalJSON_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InnerExecutionPayloadHeader_MarshalJSON_Call) RunAndReturn(run func() ([]byte, error)) *InnerExecutionPayloadHeader_MarshalJSON_Call {
	_c.Call.Return(run)
	return _c
}

// MarshalSSZ provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) MarshalSSZ() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarshalSSZ")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InnerExecutionPayloadHeader_MarshalSSZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalSSZ'
type InnerExecutionPayloadHeader_MarshalSSZ_Call struct {
	*mock.Call
}

// MarshalSSZ is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) MarshalSSZ() *InnerExecutionPayloadHeader_MarshalSSZ_Call {
	return &InnerExecutionPayloadHeader_MarshalSSZ_Call{Call: _e.mock.On("MarshalSSZ")}
}

func (_c *InnerExecutionPayloadHeader_MarshalSSZ_Call) Run(run func()) *InnerExecutionPayloadHeader_MarshalSSZ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_MarshalSSZ_Call) Return(_a0 []byte, _a1 error) *InnerExecutionPayloadHeader_MarshalSSZ_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InnerExecutionPayloadHeader_MarshalSSZ_Call) RunAndReturn(run func() ([]byte, error)) *InnerExecutionPayloadHeader_MarshalSSZ_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalJSON provides a mock function with given fields: _a0
func (_m *InnerExecutionPayloadHeader) UnmarshalJSON(_a0 []byte) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InnerExecutionPayloadHeader_UnmarshalJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalJSON'
type InnerExecutionPayloadHeader_UnmarshalJSON_Call struct {
	*mock.Call
}

// UnmarshalJSON is a helper method to define mock.On call
//   - _a0 []byte
func (_e *InnerExecutionPayloadHeader_Expecter) UnmarshalJSON(_a0 interface{}) *InnerExecutionPayloadHeader_UnmarshalJSON_Call {
	return &InnerExecutionPayloadHeader_UnmarshalJSON_Call{Call: _e.mock.On("UnmarshalJSON", _a0)}
}

func (_c *InnerExecutionPayloadHeader_UnmarshalJSON_Call) Run(run func(_a0 []byte)) *InnerExecutionPayloadHeader_UnmarshalJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_UnmarshalJSON_Call) Return(_a0 error) *InnerExecutionPayloadHeader_UnmarshalJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_UnmarshalJSON_Call) RunAndReturn(run func([]byte) error) *InnerExecutionPayloadHeader_UnmarshalJSON_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalSSZ provides a mock function with given fields: _a0
func (_m *InnerExecutionPayloadHeader) UnmarshalSSZ(_a0 []byte) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalSSZ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InnerExecutionPayloadHeader_UnmarshalSSZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalSSZ'
type InnerExecutionPayloadHeader_UnmarshalSSZ_Call struct {
	*mock.Call
}

// UnmarshalSSZ is a helper method to define mock.On call
//   - _a0 []byte
func (_e *InnerExecutionPayloadHeader_Expecter) UnmarshalSSZ(_a0 interface{}) *InnerExecutionPayloadHeader_UnmarshalSSZ_Call {
	return &InnerExecutionPayloadHeader_UnmarshalSSZ_Call{Call: _e.mock.On("UnmarshalSSZ", _a0)}
}

func (_c *InnerExecutionPayloadHeader_UnmarshalSSZ_Call) Run(run func(_a0 []byte)) *InnerExecutionPayloadHeader_UnmarshalSSZ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_UnmarshalSSZ_Call) Return(_a0 error) *InnerExecutionPayloadHeader_UnmarshalSSZ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_UnmarshalSSZ_Call) RunAndReturn(run func([]byte) error) *InnerExecutionPayloadHeader_UnmarshalSSZ_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with given fields:
func (_m *InnerExecutionPayloadHeader) Version() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// InnerExecutionPayloadHeader_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type InnerExecutionPayloadHeader_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *InnerExecutionPayloadHeader_Expecter) Version() *InnerExecutionPayloadHeader_Version_Call {
	return &InnerExecutionPayloadHeader_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *InnerExecutionPayloadHeader_Version_Call) Run(run func()) *InnerExecutionPayloadHeader_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InnerExecutionPayloadHeader_Version_Call) Return(_a0 uint32) *InnerExecutionPayloadHeader_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InnerExecutionPayloadHeader_Version_Call) RunAndReturn(run func() uint32) *InnerExecutionPayloadHeader_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewInnerExecutionPayloadHeader creates a new instance of InnerExecutionPayloadHeader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInnerExecutionPayloadHeader(t interface {
	mock.TestingT
	Cleanup(func())
}) *InnerExecutionPayloadHeader {
	mock := &InnerExecutionPayloadHeader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
