// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	bytes "github.com/berachain/beacon-kit/mod/primitives/pkg/bytes"
	common "github.com/ethereum/go-ethereum/common"

	eip4844 "github.com/berachain/beacon-kit/mod/primitives/pkg/eip4844"

	mock "github.com/stretchr/testify/mock"

	types "github.com/berachain/beacon-kit/mod/consensus-types/pkg/types"
)

// RawBeaconBlockBody is an autogenerated mock type for the RawBeaconBlockBody type
type RawBeaconBlockBody[ExecutionPayloadT interface{}] struct {
	mock.Mock
}

type RawBeaconBlockBody_Expecter[ExecutionPayloadT interface{}] struct {
	mock *mock.Mock
}

func (_m *RawBeaconBlockBody[ExecutionPayloadT]) EXPECT() *RawBeaconBlockBody_Expecter[ExecutionPayloadT] {
	return &RawBeaconBlockBody_Expecter[ExecutionPayloadT]{mock: &_m.Mock}
}

// GetBlobKzgCommitments provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) GetBlobKzgCommitments() eip4844.KZGCommitments[common.Hash] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBlobKzgCommitments")
	}

	var r0 eip4844.KZGCommitments[common.Hash]
	if rf, ok := ret.Get(0).(func() eip4844.KZGCommitments[common.Hash]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eip4844.KZGCommitments[common.Hash])
		}
	}

	return r0
}

// RawBeaconBlockBody_GetBlobKzgCommitments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlobKzgCommitments'
type RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// GetBlobKzgCommitments is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) GetBlobKzgCommitments() *RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT]{Call: _e.mock.On("GetBlobKzgCommitments")}
}

func (_c *RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT]) Return(_a0 eip4844.KZGCommitments[common.Hash]) *RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT]) RunAndReturn(run func() eip4844.KZGCommitments[common.Hash]) *RawBeaconBlockBody_GetBlobKzgCommitments_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// GetDeposits provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) GetDeposits() []*types.Deposit {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeposits")
	}

	var r0 []*types.Deposit
	if rf, ok := ret.Get(0).(func() []*types.Deposit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Deposit)
		}
	}

	return r0
}

// RawBeaconBlockBody_GetDeposits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeposits'
type RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// GetDeposits is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) GetDeposits() *RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT]{Call: _e.mock.On("GetDeposits")}
}

func (_c *RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT]) Return(_a0 []*types.Deposit) *RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT]) RunAndReturn(run func() []*types.Deposit) *RawBeaconBlockBody_GetDeposits_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// GetEth1Data provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) GetEth1Data() *types.Eth1Data {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEth1Data")
	}

	var r0 *types.Eth1Data
	if rf, ok := ret.Get(0).(func() *types.Eth1Data); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Eth1Data)
		}
	}

	return r0
}

// RawBeaconBlockBody_GetEth1Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEth1Data'
type RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// GetEth1Data is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) GetEth1Data() *RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT]{Call: _e.mock.On("GetEth1Data")}
}

func (_c *RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT]) Return(_a0 *types.Eth1Data) *RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT]) RunAndReturn(run func() *types.Eth1Data) *RawBeaconBlockBody_GetEth1Data_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// GetExecutionPayload provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) GetExecutionPayload() ExecutionPayloadT {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionPayload")
	}

	var r0 ExecutionPayloadT
	if rf, ok := ret.Get(0).(func() ExecutionPayloadT); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ExecutionPayloadT)
	}

	return r0
}

// RawBeaconBlockBody_GetExecutionPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionPayload'
type RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// GetExecutionPayload is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) GetExecutionPayload() *RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT]{Call: _e.mock.On("GetExecutionPayload")}
}

func (_c *RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT]) Return(_a0 ExecutionPayloadT) *RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT]) RunAndReturn(run func() ExecutionPayloadT) *RawBeaconBlockBody_GetExecutionPayload_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// GetGraffiti provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) GetGraffiti() bytes.B32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGraffiti")
	}

	var r0 bytes.B32
	if rf, ok := ret.Get(0).(func() bytes.B32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bytes.B32)
		}
	}

	return r0
}

// RawBeaconBlockBody_GetGraffiti_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraffiti'
type RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// GetGraffiti is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) GetGraffiti() *RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT]{Call: _e.mock.On("GetGraffiti")}
}

func (_c *RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT]) Return(_a0 bytes.B32) *RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT]) RunAndReturn(run func() bytes.B32) *RawBeaconBlockBody_GetGraffiti_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// GetRandaoReveal provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) GetRandaoReveal() bytes.B96 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRandaoReveal")
	}

	var r0 bytes.B96
	if rf, ok := ret.Get(0).(func() bytes.B96); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bytes.B96)
		}
	}

	return r0
}

// RawBeaconBlockBody_GetRandaoReveal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandaoReveal'
type RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// GetRandaoReveal is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) GetRandaoReveal() *RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT]{Call: _e.mock.On("GetRandaoReveal")}
}

func (_c *RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT]) Return(_a0 bytes.B96) *RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT]) RunAndReturn(run func() bytes.B96) *RawBeaconBlockBody_GetRandaoReveal_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// GetTopLevelRoots provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) GetTopLevelRoots() ([][32]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTopLevelRoots")
	}

	var r0 [][32]byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([][32]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() [][32]byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][32]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RawBeaconBlockBody_GetTopLevelRoots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopLevelRoots'
type RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// GetTopLevelRoots is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) GetTopLevelRoots() *RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT]{Call: _e.mock.On("GetTopLevelRoots")}
}

func (_c *RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT]) Return(_a0 [][32]byte, _a1 error) *RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT]) RunAndReturn(run func() ([][32]byte, error)) *RawBeaconBlockBody_GetTopLevelRoots_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// HashTreeRoot provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) HashTreeRoot() ([32]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HashTreeRoot")
	}

	var r0 [32]byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([32]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() [32]byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RawBeaconBlockBody_HashTreeRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashTreeRoot'
type RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// HashTreeRoot is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) HashTreeRoot() *RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT]{Call: _e.mock.On("HashTreeRoot")}
}

func (_c *RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT]) Return(_a0 [32]byte, _a1 error) *RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT]) RunAndReturn(run func() ([32]byte, error)) *RawBeaconBlockBody_HashTreeRoot_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// IsNil provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) IsNil() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNil")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RawBeaconBlockBody_IsNil_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNil'
type RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// IsNil is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) IsNil() *RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT]{Call: _e.mock.On("IsNil")}
}

func (_c *RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT]) Return(_a0 bool) *RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT]) RunAndReturn(run func() bool) *RawBeaconBlockBody_IsNil_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// Length provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) Length() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Length")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// RawBeaconBlockBody_Length_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Length'
type RawBeaconBlockBody_Length_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// Length is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) Length() *RawBeaconBlockBody_Length_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_Length_Call[ExecutionPayloadT]{Call: _e.mock.On("Length")}
}

func (_c *RawBeaconBlockBody_Length_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_Length_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_Length_Call[ExecutionPayloadT]) Return(_a0 uint64) *RawBeaconBlockBody_Length_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_Length_Call[ExecutionPayloadT]) RunAndReturn(run func() uint64) *RawBeaconBlockBody_Length_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// MarshalSSZ provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) MarshalSSZ() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarshalSSZ")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RawBeaconBlockBody_MarshalSSZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalSSZ'
type RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// MarshalSSZ is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) MarshalSSZ() *RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT]{Call: _e.mock.On("MarshalSSZ")}
}

func (_c *RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT]) Return(_a0 []byte, _a1 error) *RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT]) RunAndReturn(run func() ([]byte, error)) *RawBeaconBlockBody_MarshalSSZ_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// MarshalSSZTo provides a mock function with given fields: _a0
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) MarshalSSZTo(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for MarshalSSZTo")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RawBeaconBlockBody_MarshalSSZTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalSSZTo'
type RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// MarshalSSZTo is a helper method to define mock.On call
//   - _a0 []byte
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) MarshalSSZTo(_a0 interface{}) *RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT]{Call: _e.mock.On("MarshalSSZTo", _a0)}
}

func (_c *RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT]) Run(run func(_a0 []byte)) *RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT]) Return(_a0 []byte, _a1 error) *RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT]) RunAndReturn(run func([]byte) ([]byte, error)) *RawBeaconBlockBody_MarshalSSZTo_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// SetBlobKzgCommitments provides a mock function with given fields: _a0
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) SetBlobKzgCommitments(_a0 eip4844.KZGCommitments[common.Hash]) {
	_m.Called(_a0)
}

// RawBeaconBlockBody_SetBlobKzgCommitments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBlobKzgCommitments'
type RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// SetBlobKzgCommitments is a helper method to define mock.On call
//   - _a0 eip4844.KZGCommitments[common.Hash]
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) SetBlobKzgCommitments(_a0 interface{}) *RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT]{Call: _e.mock.On("SetBlobKzgCommitments", _a0)}
}

func (_c *RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT]) Run(run func(_a0 eip4844.KZGCommitments[common.Hash])) *RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(eip4844.KZGCommitments[common.Hash]))
	})
	return _c
}

func (_c *RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT]) Return() *RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT] {
	_c.Call.Return()
	return _c
}

func (_c *RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT]) RunAndReturn(run func(eip4844.KZGCommitments[common.Hash])) *RawBeaconBlockBody_SetBlobKzgCommitments_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// SetDeposits provides a mock function with given fields: _a0
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) SetDeposits(_a0 []*types.Deposit) {
	_m.Called(_a0)
}

// RawBeaconBlockBody_SetDeposits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeposits'
type RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// SetDeposits is a helper method to define mock.On call
//   - _a0 []*types.Deposit
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) SetDeposits(_a0 interface{}) *RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT]{Call: _e.mock.On("SetDeposits", _a0)}
}

func (_c *RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT]) Run(run func(_a0 []*types.Deposit)) *RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*types.Deposit))
	})
	return _c
}

func (_c *RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT]) Return() *RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT] {
	_c.Call.Return()
	return _c
}

func (_c *RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT]) RunAndReturn(run func([]*types.Deposit)) *RawBeaconBlockBody_SetDeposits_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// SetEth1Data provides a mock function with given fields: _a0
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) SetEth1Data(_a0 *types.Eth1Data) {
	_m.Called(_a0)
}

// RawBeaconBlockBody_SetEth1Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEth1Data'
type RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// SetEth1Data is a helper method to define mock.On call
//   - _a0 *types.Eth1Data
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) SetEth1Data(_a0 interface{}) *RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT]{Call: _e.mock.On("SetEth1Data", _a0)}
}

func (_c *RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT]) Run(run func(_a0 *types.Eth1Data)) *RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.Eth1Data))
	})
	return _c
}

func (_c *RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT]) Return() *RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT] {
	_c.Call.Return()
	return _c
}

func (_c *RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT]) RunAndReturn(run func(*types.Eth1Data)) *RawBeaconBlockBody_SetEth1Data_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// SetExecutionData provides a mock function with given fields: _a0
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) SetExecutionData(_a0 ExecutionPayloadT) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetExecutionData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ExecutionPayloadT) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RawBeaconBlockBody_SetExecutionData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExecutionData'
type RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// SetExecutionData is a helper method to define mock.On call
//   - _a0 ExecutionPayloadT
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) SetExecutionData(_a0 interface{}) *RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT]{Call: _e.mock.On("SetExecutionData", _a0)}
}

func (_c *RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT]) Run(run func(_a0 ExecutionPayloadT)) *RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ExecutionPayloadT))
	})
	return _c
}

func (_c *RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT]) Return(_a0 error) *RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT]) RunAndReturn(run func(ExecutionPayloadT) error) *RawBeaconBlockBody_SetExecutionData_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// SetRandaoReveal provides a mock function with given fields: _a0
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) SetRandaoReveal(_a0 bytes.B96) {
	_m.Called(_a0)
}

// RawBeaconBlockBody_SetRandaoReveal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRandaoReveal'
type RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// SetRandaoReveal is a helper method to define mock.On call
//   - _a0 bytes.B96
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) SetRandaoReveal(_a0 interface{}) *RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT]{Call: _e.mock.On("SetRandaoReveal", _a0)}
}

func (_c *RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT]) Run(run func(_a0 bytes.B96)) *RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bytes.B96))
	})
	return _c
}

func (_c *RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT]) Return() *RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT] {
	_c.Call.Return()
	return _c
}

func (_c *RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT]) RunAndReturn(run func(bytes.B96)) *RawBeaconBlockBody_SetRandaoReveal_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// SizeSSZ provides a mock function with given fields:
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) SizeSSZ() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SizeSSZ")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// RawBeaconBlockBody_SizeSSZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SizeSSZ'
type RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// SizeSSZ is a helper method to define mock.On call
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) SizeSSZ() *RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT]{Call: _e.mock.On("SizeSSZ")}
}

func (_c *RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT]) Run(run func()) *RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT]) Return(_a0 int) *RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT]) RunAndReturn(run func() int) *RawBeaconBlockBody_SizeSSZ_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// UnmarshalSSZ provides a mock function with given fields: _a0
func (_m *RawBeaconBlockBody[ExecutionPayloadT]) UnmarshalSSZ(_a0 []byte) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalSSZ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RawBeaconBlockBody_UnmarshalSSZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalSSZ'
type RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT interface{}] struct {
	*mock.Call
}

// UnmarshalSSZ is a helper method to define mock.On call
//   - _a0 []byte
func (_e *RawBeaconBlockBody_Expecter[ExecutionPayloadT]) UnmarshalSSZ(_a0 interface{}) *RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT] {
	return &RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT]{Call: _e.mock.On("UnmarshalSSZ", _a0)}
}

func (_c *RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT]) Run(run func(_a0 []byte)) *RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT]) Return(_a0 error) *RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT]) RunAndReturn(run func([]byte) error) *RawBeaconBlockBody_UnmarshalSSZ_Call[ExecutionPayloadT] {
	_c.Call.Return(run)
	return _c
}

// NewRawBeaconBlockBody creates a new instance of RawBeaconBlockBody. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRawBeaconBlockBody[ExecutionPayloadT interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *RawBeaconBlockBody[ExecutionPayloadT] {
	mock := &RawBeaconBlockBody[ExecutionPayloadT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
