# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config
[profile.default]
auto_detect_solc = false
solc = "0.8.26"
evm_version = "cancun"
fuzz = { runs = 1024 }
optimizer = true
optimizer_runs = 4294967295
via_ir = false
out = "out"
src = "src"
test = "test"
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
gas_reports = ["*"]
verbosity = 2
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./test"}, { access = "read", path = "./out"}]

[profile.fuzz]
fuzz = { runs = 1024 }
verbosity = 1

[profile.coverage]
fuzz = { runs = 16 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 80
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = false

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "https://sepolia.gateway.tenderly.co"
