// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	enginetypes "github.com/berachain/beacon-kit/engine/types"
	mock "github.com/stretchr/testify/mock"

	types "github.com/berachain/beacon-kit/beacon/core/types"
)

// ValsetUpdater is an autogenerated mock type for the ValsetUpdater type
type ValsetUpdater struct {
	mock.Mock
}

type ValsetUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *ValsetUpdater) EXPECT() *ValsetUpdater_Expecter {
	return &ValsetUpdater_Expecter{mock: &_m.Mock}
}

// ApplyChanges provides a mock function with given fields: _a0, _a1, _a2
func (_m *ValsetUpdater) ApplyChanges(_a0 context.Context, _a1 []*types.Deposit, _a2 []*enginetypes.Withdrawal) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ApplyChanges")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*types.Deposit, []*enginetypes.Withdrawal) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValsetUpdater_ApplyChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyChanges'
type ValsetUpdater_ApplyChanges_Call struct {
	*mock.Call
}

// ApplyChanges is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []*types.Deposit
//   - _a2 []*enginetypes.Withdrawal
func (_e *ValsetUpdater_Expecter) ApplyChanges(_a0 interface{}, _a1 interface{}, _a2 interface{}) *ValsetUpdater_ApplyChanges_Call {
	return &ValsetUpdater_ApplyChanges_Call{Call: _e.mock.On("ApplyChanges", _a0, _a1, _a2)}
}

func (_c *ValsetUpdater_ApplyChanges_Call) Run(run func(_a0 context.Context, _a1 []*types.Deposit, _a2 []*enginetypes.Withdrawal)) *ValsetUpdater_ApplyChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*types.Deposit), args[2].([]*enginetypes.Withdrawal))
	})
	return _c
}

func (_c *ValsetUpdater_ApplyChanges_Call) Return(_a0 error) *ValsetUpdater_ApplyChanges_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ValsetUpdater_ApplyChanges_Call) RunAndReturn(run func(context.Context, []*types.Deposit, []*enginetypes.Withdrawal) error) *ValsetUpdater_ApplyChanges_Call {
	_c.Call.Return(run)
	return _c
}

// NewValsetUpdater creates a new instance of ValsetUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValsetUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValsetUpdater {
	mock := &ValsetUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
