# Mainnet Chain Spec Configuration

# Gwei value constants
max-effective-balance = 10000000000000000
ejection-balance = 240000000000000
effective-balance-increment = 10000000000000

# Hysteresis parameters
hysteresis-quotient = 4
hysteresis-downward-multiplier = 1
hysteresis-upward-multiplier = 5

# Time parameters
slots-per-epoch = 192
slots-per-historical-root = 8
min-epochs-to-inactivity-penalty = 4

# Signature domains (each will be interpreted as a numeric value)
domain-type-beacon-proposer = 0
domain-type-beacon-attester = 1
domain-type-randao = 2
domain-type-deposit = 3
domain-type-voluntary-exit = 4
domain-type-selection-proof = 5
domain-type-aggregate-and-proof = 6
domain-type-application-mask = 16777216


# Eth1-related values
deposit-contract-address = "0x4242424242424242424242424242424242424242"
max-deposits-per-block = 16
deposit-eth1-chain-id = 80094
eth1-follow-distance = 1
target-seconds-per-eth1-block = 2

# Fork-related values
genesis-time = 1737381600
deneb-one-fork-time = 1738415507
electra-fork-time = 9999999999999999

# State list lengths
epochs-per-historical-vector = 8
epochs-per-slashings-vector = 8
historical-roots-limit = 8
validator-registry-limit = 1099511627776

# Rewards and penalties constants
#inactivity-penalty-quotient = 33554432
#proportional-slashing-multiplier = 2

# Capella values
max-withdrawals-per-payload = 16
max-validators-per-withdrawals-sweep = 31

# Deneb values
min-epochs-for-blobs-sidecars-request = 4096
max-blob-commitments-per-block = 4096
max-blobs-per-block = 6
field-elements-per-blob = 4096
bytes-per-blob = 131072
kzg-commitment-inclusion-proof-depth = 17

# Berachain genesis values
validator-set-cap = 69
evm-inflation-address = "0x0000000000000000000000000000000000000000"
evm-inflation-per-block = 0

# Deneb1 value changes
evm-inflation-address-deneb-one = "0x656b95E550C07a9ffe548bd4085c72418Ceb1dba"
evm-inflation-per-block-deneb-one = 5750000000
