name: comet-e2e
# Runs the CI end-to-end test network on all pushes to main or release branches
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch:  # allow running workflow manually
  pull_request:
  merge_group:
  push:
    branches:
      - greg/e2e-framework

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  e2e-test:
    # Run two parallel jobs: for `ci.toml`, and for the regression manifests
    strategy:
      fail-fast: false
      matrix:
        group: ['testing/networks/ci']
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          
      - uses: actions/checkout@v4

      - name: Build
        working-directory: .
        run: make build-cmt-e2e

      - name: Run "${{ matrix.group }}" testnet
        working-directory: .
        run: make test-cmt-e2e-single-no-build